config/routes.rb
Rails.application.routes.draw do
  # ルート
  root 'static_pages#index'

  # セッション
  get     '/login'  =>  'sessions#login_form'
  post    '/login'  =>  'sessions#login'
  delete  '/logout' =>  'sessions#logout'
  
  # ホーム
  get     '/index'  =>  'static_pages#index'

  # 検索
  get     '/search'                 => 'search#index'
  get     '/search/show_books'      => 'search#show_books'
  get     '/search/show_knowledges' => 'search#show_knowledges'
  get     '/search/show_tags'       => 'search#show_tags'

  # ナレッジ
  resources :knowledges do
    collection do
      get :search
    end
  end

  # ブック
  resources :books do
    resources :book_knowledges, only: [:show]
  end

  # タグ
  resources :tags, only: [:index, :create, :destroy] do
    member do
      get :show_books
      get :show_knowledges
    end

    collection do
      get :search
    end
  end

  # ユーザ
  resource :user

  # 自分の投稿
  resources :posts, only: [:index] do
    collection do
      get :show_books
      get :show_knowledges
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :is_user_logged_in

  def index
    unless params[:q] == nil
      @search_word = params[:q]

      @books = Book.search(@search_word).limit(5)
      @book_tags = get_tag(@books)

      @knowledges = Knowledge.search(@search_word).limit(5)
      @knowledge_tags = get_tag(@knowledges)

      @tags = Tag.search(@search_word).limit(5)
    else
      flash[:danger] = "検索パラメータが不足しています"
      redirect_to index_url
    end
  end
  
  def show_books
    unless params[:q] == nil
      @search_word = params[:q]
      @books = Book.search(@search_word)
      @book_tags = get_tag(@books)
      @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
    else
      flash[:danger] = "検索パラメータが不足しています"
      redirect_to index_url
    end
  end

  def show_knowledges
    unless params[:q] == nil
      @search_word = params[:q]
      @knowledges = Knowledge.search(@search_word)
      @knowledge_tags = get_tag(@knowledges)
      @knowledges = Kaminari.paginate_array(@knowledges).page(params[:page]).per(5)
    else
      flash[:danger] = "検索パラメータが不足しています"
      redirect_to index_url
    end
  end

  def show_tags
    unless params[:q] == nil
      @search_word = params[:q]
      @tags = Tag.search(@search_word)
      @tags = Kaminari.paginate_array(@tags).page(params[:page]).per(5)
    else
      flash[:danger] = "検索パラメータが不足しています"
      redirect_to index_url
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class='container'>

  <% breadcrumb :search %>

  <!-- ヘッダ部 -->
  <h1 class="my-3">検索結果：<%= @search_word %></h1>
  <hr>

  <div class="card mt-3">
    <div class="card-header">
      <i class="fas fa-book"></i>&nbsp;&nbsp;ブック
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% cnt = 0 %>
        <% @books.each do |book| %>
        <li class="list-group-item">
          <!-- タイトル -->
          <strong><%= link_to book.title, book_path(book) %></strong>
          <small class="text-muted float-right">最終更新 : <%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
          <br>
          <!-- タグ -->
          <% @book_tags[cnt].each do |tag| %>
          <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
          <% end %>
          <br>
        </li>
        <% cnt += 1 %>
        <% end %>
        <li class="list-group-item text-center">
          <%= link_to "もっと見る", search_show_books_path(q: @search_word) %>
        </li>
      </ul>
    </div>
  </div>

  <div class="card my-5">
    <div class="card-header">
      <i class="far fa-lightbulb"></i>&nbsp;&nbsp;ナレッジ
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% cnt = 0 %>
        <% @knowledges.each do |knowledge| %>
        <li class="list-group-item">
          <!-- タイトル -->
          <strong><%= link_to knowledge.title, knowledge_path(knowledge) %></strong>
          <small class="text-muted float-right">最終更新 : <%= knowledge.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
          <br>
          <!-- タグ -->
          <% @knowledge_tags[cnt].each do |tag| %>
          <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
          <% end %>
          <br>
        </li>
        <% cnt += 1 %>
        <% end %>
        <li class="list-group-item text-center">
          <%= link_to "もっと見る", search_show_knowledges_path(q: @search_word) %>
        </li>
      </ul>
    </div>
  </div>

  <div class="card my-5">
    <div class="card-header">
      <i class="fas fa-tags"></i>&nbsp;&nbsp;タグ
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% cnt = 0 %>
        <% @tags.each do |tag| %>
        <li class="list-group-item">
          <!-- タグ名 -->
          <strong><%= link_to "#" + tag.name, show_books_tag_path(tag) %></strong>
          <br><br>
        </li>
        <% cnt += 1 %>
        <% end %>
        <li class="list-group-item text-center">
          <%= link_to "もっと見る", search_show_tags_path(q: @search_word) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/search/show_books.html.erb
<div class="container">

  <% breadcrumb :search_books %>

  <h1 class="my-3">ブック検索結果：<%= @search_word %></h1>
  <hr>

  <ul class="list-group">
    <% cnt = 0 %>
    <% @books.each do |book| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to book.title, book_path(book) %></strong>
      <small class="text-muted float-right">最終更新 : <%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
      <br>
      <!-- タグ -->
      <% @book_tags[cnt].each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
      <% end %>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>

  <p class="text-center"><%= page_entries_info @books %></p>
  <%= paginate @books %>
</div>

app/views/search/show_knowledges.html.erb
<div class="container">

  <% breadcrumb :search_knowledges %>

  <h1 class="my-3">ナレッジ検索結果：<%= @search_word %></h1>
  <hr>

  <ul class="list-group">
    <% cnt = 0 %>
    <% @knowledges.each do |knowledge| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to knowledge.title, knowledge_path(knowledge) %></strong>
      <small class="text-muted float-right">最終更新 : <%= knowledge.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
      <br>
      <!-- タグ -->
      <% @knowledge_tags[cnt].each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
      <% end %>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>

  <p class="text-center"><%= page_entries_info @knowledges %></p>
  <%= paginate @knowledges %>
</div>

app/views/search/show_tags.html.erb
<div class="container">

  <% breadcrumb :search_tags %>

  <h1 class="my-3">タグ検索結果：<%= @search_word %></h1>
  <hr>

  <ul class="list-group">
    <% cnt = 0 %>
    <% @tags.each do |tag| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to "#" + tag.name, show_books_tag_path(tag) %></strong>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>

  <p class="text-center"><%= page_entries_info @tags %></p>
  <%= paginate @tags %>
</div>