config/routes.rb
Rails.application.routes.draw do
  # ルート
  root 'static_pages#index'

  # セッション
  get     '/login'  =>  'sessions#login_form'
  post    '/login'  =>  'sessions#login'
  delete  '/logout' =>  'sessions#logout'
  
  # ホーム
  get     '/index'  =>  'static_pages#index'

  # 検索
  get     '/search'                 => 'search#index'
  get     '/search/show_books'      => 'search#show_books'
  get     '/search/show_knowledges' => 'search#show_knowledges'
  get     '/search/show_tags'       => 'search#show_tags'

  # ナレッジ
  resources :knowledges do
    collection do
      get :search
    end
  end

  # ブック
  resources :books do
    resources :book_knowledges, only: [:show]
  end

  # タグ
  resources :tags, only: [:index, :create, :destroy] do
    member do
      get :show_books
      get :show_knowledges
    end

    collection do
      get :search
    end
  end

  # ユーザ
  resource :user

  # 自分の投稿
  resources :posts, only: [:index] do
    collection do
      get :show_books
      get :show_knowledges
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many  :book_tags
  has_many  :books, through: :book_tags
  has_many  :knowledge_tags
  has_many  :knowledges, through: :knowledge_tags

  validates :name, presence: true, uniqueness: true

  scope :search, -> (word) { where('name LIKE ?', '%' + word + '%') }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :is_user_logged_in

  def index
    @tags = Tag.all.page(params[:page]).per(40)
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "タグを登録しました"
      redirect_to tags_url
    else
      flash[:danger] = "タグの登録に失敗しました"
      redirect_to tags_url
    end
  end

  def destroy
    Tag.find(params[:id]).destroy
    flash[:success] = "タグを削除しました"
    redirect_to tags_url
  end

  def show_books
    @tag = Tag.find(params[:id])
    @books = Book.find(@tag.book_ids)
    @book_tags = get_tag(@books)
    @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  end

  def show_knowledges
    @tag = Tag.find(params[:id])
    @knowledges = Knowledge.find(@tag.knowledge_ids)
    @knowledge_tags = get_tag(@knowledges)
    @knowledges = Kaminari.paginate_array(@knowledges).page(params[:page]).per(5)
  end

  def search
    @tags = Tag.search(params[:q])
    render json: @tags
  end

  private
    def tag_params
      params.permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<div class="container">

  <% breadcrumb :tags %>

  <div class="form-inline my-5">
    <%= form_tag(tags_path, method: :post, class: "mx-auto") do %>
      <%= text_field_tag :name,'', class: "form-control mr-2", placeholder: "新規タグ名を入力" %>
      <%= submit_tag 'タグを登録', class: "btn btn-success" %>
    <% end %>
  </div>

  <div class="d-flex flex-row flex-wrap">
    <% @tags.each do |tag| %>
      <div class="col-3">
        <div class="card my-3">
          <div class="card-body">
            <strong><%= link_to "#" + tag.name, show_books_tag_path(tag) %></strong>
            <%= link_to tag_path(tag), method: :delete, data: {confirm: "#{tag.name}を削除しますか？"}, class: "btn btn-sm btn-outline-danger float-right" do %>
              <i class="fas fa-times"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= paginate @tags %>
</div>

app/views/tags/show_books.html.erb
<div class="container">

  <% breadcrumb :show_tag, @tag %>

  <!-- ヘッダ部 -->
  <h1 class="my-3">#<%= @tag.name %></h1>
  <hr>

  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <%= link_to "ブック", "#", class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "ナレッジ", show_knowledges_tag_path(@tag.id), class: "nav-link" %>
    </li>
  </ul>

  <!-- コンテンツ部 -->
  <ul class="list-group mt-4">
    <% cnt = 0 %>
    <% @books.each do |book| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to book.title, book_path(book) %></strong>
      <small class="text-muted float-right">最終更新 : <%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
      <br>
      <!-- タグ -->
      <% @book_tags[cnt].each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
      <% end %>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>
</div>

app/views/tags/show_knowledges.html.erb
<div class="container">

  <% breadcrumb :show_tag, @tag %>

  <!-- ヘッダ部 -->
  <h1 class="my-3">#<%= @tag.name %></h1>
  <hr>

  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <%= link_to "ブック", show_books_tag_path(@tag.id), class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "ナレッジ", "#", class: "nav-link active" %>
    </li>
  </ul>

  <!-- コンテンツ部 -->
  <ul class="list-group mt-4">
    <% cnt = 0 %>
    <% @knowledges.each do |knowledge| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to knowledge.title, knowledge_path(knowledge) %></strong>
      <small class="text-muted float-right">最終更新 : <%= knowledge.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
      <br>
      <!-- タグ -->
      <% @knowledge_tags[cnt].each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
      <% end %>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>
</div>