config/routes.rb
Rails.application.routes.draw do
  # ルート
  root 'static_pages#index'

  # セッション
  get     '/login'  =>  'sessions#login_form'
  post    '/login'  =>  'sessions#login'
  delete  '/logout' =>  'sessions#logout'
  
  # ホーム
  get     '/index'  =>  'static_pages#index'

  # 検索
  get     '/search'                 => 'search#index'
  get     '/search/show_books'      => 'search#show_books'
  get     '/search/show_knowledges' => 'search#show_knowledges'
  get     '/search/show_tags'       => 'search#show_tags'

  # ナレッジ
  resources :knowledges do
    collection do
      get :search
    end
  end

  # ブック
  resources :books do
    resources :book_knowledges, only: [:show]
  end

  # タグ
  resources :tags, only: [:index, :create, :destroy] do
    member do
      get :show_books
      get :show_knowledges
    end

    collection do
      get :search
    end
  end

  # ユーザ
  resource :user

  # 自分の投稿
  resources :posts, only: [:index] do
    collection do
      get :show_books
      get :show_knowledges
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    redirect_to show_books_posts_path
  end

  def show_books
    @books = Book.where(user_id: current_user.id)
    @book_tags = get_tag(@books)
    @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  end

  def show_knowledges
    @knowledges = Knowledge.where(user_id: current_user.id)
    @knowledge_tags = get_tag(@knowledges)
    @knowledges = Kaminari.paginate_array(@knowledges).page(params[:page]).per(5)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/show_books.html.erb
<div class="container">

  <% breadcrumb :posts %>

  <!-- ヘッダ部 -->
  <h1 class="my-3">自分の投稿</h1>
  <hr>

  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <%= link_to "ブック", "#", class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "ナレッジ", show_knowledges_posts_path, class: "nav-link" %>
    </li>
  </ul>

  <!-- コンテンツ部 -->
  <ul class="list-group mt-4">
    <% cnt = 0 %>
    <% @books.each do |book| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to book.title, book_path(book) %></strong>
      <%= link_to  "削除", book_path(book), method: :delete, class: "btn btn-danger float-right", data: {confirm: "#{book.title}を削除しますか？"} %>
      <%= link_to  "修正", edit_book_path(book), class: "btn btn-success float-right mr-4" %>
      <small class="text-muted float-right mr-4">最終更新 : <%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
      <br>
      <!-- タグ -->
      <% @book_tags[cnt].each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
      <% end %>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>

  <p class="text-center"><%= page_entries_info @books %></p>
  <%= paginate @books %>
</div>

app/views/posts/show_knowledges.html.erb
<div class="container">

  <% breadcrumb :posts %>

  <!-- ヘッダ部 -->
  <h1 class="my-3">自分の投稿</h1>
  <hr>

  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <%= link_to "ブック", show_books_posts_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "ナレッジ", "#", class: "nav-link active" %>
    </li>
  </ul>

  <!-- コンテンツ部 -->
  <ul class="list-group mt-4">
    <% cnt = 0 %>
    <% @knowledges.each do |knowledge| %>
    <li class="list-group-item">
      <!-- タイトル -->
      <strong><%= link_to knowledge.title, knowledge_path(knowledge) %></strong>
      <%= link_to  "削除", knowledge_path(knowledge), method: :delete, class: "btn btn-danger float-right", data: {confirm: "#{knowledge.title}を削除しますか？"} %>
      <%= link_to  "修正", edit_knowledge_path(knowledge), class: "btn btn-success float-right mr-4" %>
      <small class="text-muted float-right mr-4">最終更新 : <%= knowledge.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
      <br>
      <!-- タグ -->
      <% @knowledge_tags[cnt].each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag.name %></span>&nbsp;
      <% end %>
      <br>
    </li>
    <% cnt += 1 %>
    <% end %>
  </ul>
  <br>

  <p class="text-center"><%= page_entries_info @knowledges %></p>
  <%= paginate @knowledges %>
</div>