config/routes.rb
Rails.application.routes.draw do
  # ルート
  root 'static_pages#index'

  # セッション
  get     '/login'  =>  'sessions#login_form'
  post    '/login'  =>  'sessions#login'
  delete  '/logout' =>  'sessions#logout'
  
  # ホーム
  get     '/index'  =>  'static_pages#index'

  # 検索
  get     '/search'                 => 'search#index'
  get     '/search/show_books'      => 'search#show_books'
  get     '/search/show_knowledges' => 'search#show_knowledges'
  get     '/search/show_tags'       => 'search#show_tags'

  # ナレッジ
  resources :knowledges do
    collection do
      get :search
    end
  end

  # ブック
  resources :books do
    resources :book_knowledges, only: [:show]
  end

  # タグ
  resources :tags, only: [:index, :create, :destroy] do
    member do
      get :show_books
      get :show_knowledges
    end

    collection do
      get :search
    end
  end

  # ユーザ
  resource :user

  # 自分の投稿
  resources :posts, only: [:index] do
    collection do
      get :show_books
      get :show_knowledges
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to  :user, optional: true
  has_many    :book_knowledges
  has_many    :knowledges, through: :book_knowledges
  has_many    :book_tags
  has_many    :tags, through: :book_tags

  validates :title, presence: true

  scope :search, -> (word) { where('title LIKE ?', '%' + word + '%') }
end

app/models/book_knowledge.rb
class BookKnowledge < ApplicationRecord
  belongs_to  :book, optional: true
  belongs_to  :knowledge, optional: true
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to  :book, optional: true
  belongs_to  :tag
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to    :user, optional: true
  has_many      :book_knowledges
  has_many      :books, through: :book_knowledges
  has_many      :knowledge_tags
  has_many      :tags, through: :knowledge_tags
  has_rich_text :content

  validates     :title, presence: true

  scope :search, -> (word) { where('title LIKE ?', '%' + word + '%') }
end

app/models/knowledge_tag.rb
class KnowledgeTag < ApplicationRecord
  belongs_to  :knowledge, optional: true
  belongs_to  :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many  :book_tags
  has_many  :books, through: :book_tags
  has_many  :knowledge_tags
  has_many  :knowledges, through: :knowledge_tags

  validates :name, presence: true, uniqueness: true

  scope :search, -> (word) { where('name LIKE ?', '%' + word + '%') }
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :book
  has_many  :knowledge
  has_secure_password

  validates :login_id, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_user_logged_in

  def index
    @books = Book.all.page(params[:page]).per(5)
    @tags = get_tag(@books)
  end

  def show
    @book = Book.find(params[:id])
    @tags = Tag.find(@book.tag_ids)

    @knowledges = Knowledge.find(@book.knowledge_ids)
    @knowledge_tags = get_tag(@knowledges)
    @knowledges = Kaminari.paginate_array(@knowledges).page(params[:page]).per(5)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_entry_params)

    if @book.save!
      flash[:success] = "ブックの登録が完了しました"
      redirect_to books_url
    else
      flash.now[:danger] = "ブックの登録に失敗しました"
      render action: :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_entry_params)
      flash[:success] = "ブックの更新が完了しました"
      redirect_to books_url
    else
      flash[:danger] = "ブックの更新に失敗しました"
      render action: :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "ブックの削除が完了しました"
    redirect_to books_url
  end

  private
    def book_search_params
    end

    def book_entry_params
      params.require(:book).permit(:title, :detail, :user_id, knowledge_ids: [], tag_ids: [])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    redirect_to show_books_posts_path
  end

  def show_books
    @books = Book.where(user_id: current_user.id)
    @book_tags = get_tag(@books)
    @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  end

  def show_knowledges
    @knowledges = Knowledge.where(user_id: current_user.id)
    @knowledge_tags = get_tag(@knowledges)
    @knowledges = Kaminari.paginate_array(@knowledges).page(params[:page]).per(5)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :is_user_logged_in

  def index
    @tags = Tag.all.page(params[:page]).per(40)
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "タグを登録しました"
      redirect_to tags_url
    else
      flash[:danger] = "タグの登録に失敗しました"
      redirect_to tags_url
    end
  end

  def destroy
    Tag.find(params[:id]).destroy
    flash[:success] = "タグを削除しました"
    redirect_to tags_url
  end

  def show_books
    @tag = Tag.find(params[:id])
    @books = Book.find(@tag.book_ids)
    @book_tags = get_tag(@books)
    @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  end

  def show_knowledges
    @tag = Tag.find(params[:id])
    @knowledges = Knowledge.find(@tag.knowledge_ids)
    @knowledge_tags = get_tag(@knowledges)
    @knowledges = Kaminari.paginate_array(@knowledges).page(params[:page]).per(5)
  end

  def search
    @tags = Tag.search(params[:q])
    render json: @tags
  end

  private
    def tag_params
      params.permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ブック/ナレッジが所持しているタグを取得
  def get_tag(objs)
    tags = []
    objs.each do |obj|
      tag = Tag.find(obj.tag_ids)
      tags.push(tag)
    end
    return tags
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/knowledges_helper.rb
module KnowledgesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def is_user_logged_in
    unless logged_in?
      flash[:info] = 'ログインしてください'
      redirect_to login_url
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <div align="center"><small class="text-muted">Bluemine  ©️ 2020 hato</small></div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">

      <%= link_to index_path, id: 'logo', class: 'navbar-brand' do %>
        <%= image_tag 'logo.png', size: "45x45" %>
      <% end %>

      <!-- ブランドロゴ -->
      <button class="navbar-toggler navbar-toggle-right" type="button" data-toggle="collapse" data-target="#menu">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- navbarメニュー -->
      <div id="menu" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to books_path, class: 'nav-link' do %>
              <i class="fas fa-book"></i> ブック
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to knowledges_path, class: 'nav-link' do %>
              <i class="far fa-lightbulb"></i> ナレッジ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to tags_path, class: 'nav-link' do %>
              <i class="fas fa-tags"></i> タグ
            <% end %>
          </li>
        </ul>

        <!-- 検索バー -->
        <div class="form-inline my-2 mr-5">
          <%= form_tag(search_path, method: :get, class: "mx-auto") do %>
            <%= text_field_tag :q, '', class: "form-control mr-2", placeholder: "キーワードで検索" %>
            <%= submit_tag '検索', :name => nil, class: "btn btn-outline-primary" %>
          <% end %>
        </div>

        <!-- ユーザメニュー -->
        <ul class="navbar-nav">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user"></i>
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to show_books_posts_path, method: 'get', class: 'dropdown-item mb-1' do %>
                <i class="far fa-newspaper"></i>&nbsp;&nbsp;&nbsp;自分の投稿
              <% end %>
              <%= link_to "#", method: 'get', class: 'dropdown-item disabled mb-1' do %>
                <i class="far fa-star"></i>&nbsp;&nbsp;&nbsp;お気に入り
              <% end %>
              <%= link_to user_path, method: 'get', class: 'dropdown-item mb-1' do %>
                <i class="fas fa-cog"></i>&nbsp;&nbsp;&nbsp;ユーザ設定
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to logout_path, method: 'delete', class: 'dropdown-item' do %>
                <i class="fas fa-power-off"></i>&nbsp;&nbsp;&nbsp;ログアウト
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bluemine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ヘッダ -->
    <% if logged_in? %>
    <%= render 'layouts/header' %>
    <% end %>
    
    <div class='container'>
      <!-- パンくずリスト -->
      <div class="mt-3"><%= breadcrumbs %></div>

      <!-- フラッシュ -->
      <% flash.each do |type, msg| %>
        <div class='alert alert-<%= type %> mt-3'><%= msg %></div>
      <% end %>

      <!-- 本文 -->
      <%= yield %>
    </div>
  </body>
</html>